/**
 * 政策变更日志 — 2025-2026 美国关税政策重大变化
 *
 * 数据来源：White House, CBP, USTR, Federal Register, SCOTUS
 * 免责声明：仅供产品演示参考，实际政策以官方公告为准。
 */

import type { TariffChangeEntry, DataSourceHealth } from '@/types'

// ============================================================
// 政策变更时间线
// ============================================================

export const TARIFF_CHANGE_LOG: TariffChangeEntry[] = [
  {
    id: 'ieepa-2025-04-09',
    date: '2025-04-09',
    title: 'IEEPA 对等关税生效',
    description: '总统基于 IEEPA 宣布对等关税：中国 34%、欧盟 20%、越南 46%、日本 24%、韩国 25%、新加坡 10%、墨西哥 25%、加拿大 25%',
    tariffType: 'ieepa_historical',
    affectedOrigins: ['CN', 'EU', 'VN', 'JP', 'KR', 'SG', 'MX', 'CA'],
    changeDirection: 'new',
    changeAmount: '10%-46%',
    sourceUrl: 'https://www.whitehouse.gov/presidential-actions/',
    sourceAuthority: 'White House',
    effectiveDate: '2025-04-09',
    confidence: 'high',
  },
  {
    id: 'de-minimis-cn-hk-2025-05-02',
    date: '2025-05-02',
    title: 'De Minimis 中国/香港先行暂停',
    description: 'CBP 开始暂停中国和香港原产商品的 de minimis ($800) 免税待遇',
    tariffType: 'mfn',
    affectedOrigins: ['CN', 'HK'],
    changeDirection: 'suspended',
    sourceUrl: 'https://www.cbp.gov/newsroom/national-media-release/',
    sourceAuthority: 'CBP',
    effectiveDate: '2025-05-02',
    confidence: 'high',
  },
  {
    id: 'de-minimis-global-2025-08-29',
    date: '2025-08-29',
    title: 'De Minimis 全球暂停',
    description: 'CBP 扩大执行范围，全球所有原产地的 de minimis ($800) 免税待遇暂停',
    tariffType: 'mfn',
    affectedOrigins: ['ALL'],
    changeDirection: 'suspended',
    sourceUrl: 'https://www.cbp.gov/document/fact-sheets/factsheet-suspension-duty-free-de-minimis-treatment',
    sourceAuthority: 'CBP',
    effectiveDate: '2025-08-29',
    confidence: 'high',
  },
  {
    id: 'scotus-ieepa-2026-02-20',
    date: '2026-02-20',
    title: 'SCOTUS 推翻 IEEPA 对等关税',
    description: '最高法院在 Learning Resources, Inc. v. Trump 案中裁定 IEEPA 不授权总统征收关税，所有 IEEPA 对等关税失效',
    tariffType: 'ieepa_historical',
    affectedOrigins: ['CN', 'EU', 'VN', 'JP', 'KR', 'SG', 'MX', 'CA'],
    changeDirection: 'expired',
    sourceUrl: 'https://supreme.justia.com/cases/federal/us/607/24-1287/',
    sourceAuthority: 'SCOTUS',
    effectiveDate: '2026-02-20',
    confidence: 'high',
  },
  {
    id: 'section122-2026-02-24',
    date: '2026-02-24',
    title: 'Section 122 临时进口附加税生效',
    description: '白宫基于 Trade Act of 1974 Section 122 征收 10% 临时进口附加税，150 天期限，USMCA 国家豁免',
    tariffType: 'section122',
    affectedOrigins: ['CN', 'EU', 'VN', 'JP', 'KR', 'SG', 'DE', 'RO'],
    changeDirection: 'new',
    changeAmount: '10%',
    sourceUrl: 'https://www.whitehouse.gov/fact-sheets/2026/02/',
    sourceAuthority: 'White House',
    effectiveDate: '2026-02-24',
    confidence: 'medium',
  },
  {
    id: 'section301-ev-2024-09-27',
    date: '2024-09-27',
    title: 'Section 301 电动汽车 100% 关税生效',
    description: 'USTR 对中国原产电动汽车征收 100% Section 301 关税，半导体 50%、太阳能电池 50% 同步生效',
    tariffType: 'section301',
    affectedOrigins: ['CN'],
    affectedChapters: ['8703', '8541', '8501'],
    changeDirection: 'increase',
    changeAmount: 'EV 100%, Semi 50%, Solar 50%',
    sourceUrl: 'https://ustr.gov/issue-areas/enforcement/section-301-investigations/',
    sourceAuthority: 'USTR',
    effectiveDate: '2024-09-27',
    confidence: 'high',
  },
  {
    id: 'section232-autos-2025-05-01',
    date: '2025-05-01',
    title: 'Section 232 扩展至汽车及零部件',
    description: 'Section 232 关税从钢铁铝制品扩展至整车及零部件，统一 25% 税率',
    tariffType: 'section232',
    affectedOrigins: ['ALL'],
    affectedChapters: ['8703', '8708'],
    changeDirection: 'new',
    changeAmount: '25%',
    sourceUrl: 'https://www.cbp.gov/trade/programs-administration/',
    sourceAuthority: 'CBP',
    effectiveDate: '2025-05-01',
    confidence: 'high',
  },
]

// ============================================================
// 数据源健康状态（模拟 — 实际由后端 API 提供）
// ============================================================

export const MOCK_DATA_HEALTH: DataSourceHealth[] = [
  {
    id: 'ushts',
    name: 'USITC HTS 税率表',
    sourceUrl: 'https://hts.usitc.gov',
    lastSyncAt: '2026-01-01T00:00:00Z',
    version: '2026.HTS',
    recordCount: 18927,
    freshness: 'stale',
    failureCount: 0,
    method: '年度批量下载 JSON',
  },
  {
    id: 'ustr-section301',
    name: 'USTR Section 301 清单',
    sourceUrl: 'https://ustr.gov',
    lastSyncAt: '2026-04-15T00:00:00Z',
    version: '2026.04.15',
    recordCount: 12847,
    freshness: 'fresh',
    failureCount: 0,
    method: '网页爬取 + GitHub 数据文件',
  },
  {
    id: 'cbp-deminimis',
    name: 'CBP De Minimis 执行公告',
    sourceUrl: 'https://www.cbp.gov',
    lastSyncAt: '2026-04-10T00:00:00Z',
    version: '2026.04.10',
    recordCount: 3,
    freshness: 'fresh',
    failureCount: 0,
    method: '公告爬取',
  },
  {
    id: 'federal-register',
    name: 'Federal Register AD/CVD',
    sourceUrl: 'https://www.federalregister.gov',
    lastSyncAt: '2026-04-10T00:00:00Z',
    version: '2026.04.10',
    recordCount: 584,
    freshness: 'fresh',
    failureCount: 0,
    method: 'API 查询',
  },
  {
    id: 'section122',
    name: 'Section 122 白宫公告',
    sourceUrl: 'https://www.whitehouse.gov',
    lastSyncAt: '2026-04-15T00:00:00Z',
    version: '2026.04.15',
    recordCount: 1,
    freshness: 'fresh',
    failureCount: 0,
    method: '公告爬取',
  },
  {
    id: 'ieepa-scotus',
    name: 'IEEPA SCOTUS 判决',
    sourceUrl: 'https://supreme.justia.com',
    lastSyncAt: '2026-04-15T00:00:00Z',
    version: '2026.04.15',
    recordCount: 1,
    freshness: 'fresh',
    failureCount: 0,
    method: '判决书提取',
  },
  {
    id: 'section232',
    name: 'Section 232 钢铝汽车',
    sourceUrl: 'https://www.cbp.gov',
    lastSyncAt: '2026-04-15T00:00:00Z',
    version: '2026.04.15',
    recordCount: 1847,
    freshness: 'fresh',
    failureCount: 0,
    method: 'HS 章节映射 + CBP 执行指引',
  },
]
